### ISSUE TITLE
returns no feeds

### ISSUE THREAD

**Issue by MrGeorgen** [cristoper/feedmixer#15]
after running a simple test, the items array is empty
```
[mrgeorgen@mrgPC ~/.newsboat]$ http localhost:8080/json 'f==https://videos.lukesmith.xyz/feeds/videos.atom?videoChannelId=2' 'F==https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA' n==20 full==true 
HTTP/1.1 200 OK 
Connection: close 
Date: Mon, 25 Jan 2021 09:48:26 GMT 
Server: gunicorn/20.0.4 
content-length: 370 
content-type: application/json 
x-fm-errors: %7B%22https%3A//videos.lukesmith.xyz/feeds/videos.atom%3FvideoChannelId%3D2%22%3A%20%22%27NoneType%27%20object%20has%20no%20attribute%20%27get%27%22%7D 
{ 
    "description": "json feed created by FeedMixer.", 
    "home_page_url": "http://localhost:8080/json?f=https%3A%2F%2Fvideos.lukesmith.xyz%2Ffeeds%2Fvideos.atom%3FvideoChannelId%3D2&F=https%3A%2F%2Fwww.youtube.com%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUC7YOGHUfC1Tb6E4pudI9STA&n=20&full=true", 
    "items": [], 
    "title": "FeedMixer feed", 
    "version": "https://jsonfeed.org/version/1" 
} 
```

**Comment by cristoper** [comment]
I believe the problem is actually the uppercase F in the second query string. If I change this:

> http localhost:8080/json 'f==https://videos.lukesmith.xyz/feeds/videos.atom?videoChannelId=2' 'F==https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA' n==20 full==true

to this:

> http localhost:8080/json 'f==https://videos.lukesmith.xyz/feeds/videos.atom?videoChannelId=2' 'f==https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA' n==20 full==true

then I get a valid feed in return.

I'm keeping this open because there should be better error reporting when feedmixer can't understand a query parameter.

**Comment by MrGeorgen** [comment]
> I believe the problem is actually the uppercase F in the second query string. If I change this:
> 
> > http localhost:8080/json 'f==https://videos.lukesmith.xyz/feeds/videos.atom?videoChannelId=2' 'F==https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA' n==20 full==true
> 
> to this:
> 
> > http localhost:8080/json 'f==https://videos.lukesmith.xyz/feeds/videos.atom?videoChannelId=2' 'f==https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA' n==20 full==true
> 
> then I get a feed with items.
> 
> I'm keeping this open because there should be better error reporting when feedmixer can't understand a query parameter.

I still get no items after changing the command

**Comment by MrGeorgen** [comment]
ok it works now. I used my patch before that seems to have messed something up
